name: AsgAI
version: '1'
main: ahjd.asgAI.AsgAI
api-version: '1.21'
authors: [ ahjd ]
description: 'Advanced Mob AI API for Minecraft Paper servers'
website: 'https://github.com/yourusername/AsgAI'
load: STARTUP

depend: [ProtocolLib]

commands:
  aitest:
    description: 'AsgAI custom system commands'
    usage: '/aitest [sensor|memory]'
  mob:
    description: 'AI Mob management commands'
    usage: '/mob <spawn|list|debug|sensors|cleanup> [args]'
